### ISSUE TITLE
Repo organization and junk in repo

### ISSUE THREAD

**Issue by jbrucker** [Karczel/Trend-of-Currency#1]
Good to see that you are committing work on your project.
Your repo needs some fixes:

1. remove `.idea` and `__pycache__` (don't commit these files)
2. add a `.gitignore` and be sure it includes the directories listed above
3. put images in a subdirectory, typically named `images` or `assets`. This is good style but not as important as items 1 and 2.

To remove `.idea` from git **without** removing it from your working copy,
use:
```
git rm -r --cached .idea
```
likewise for `__pycache__`.  Then commit the changes.

To move a git-tracked file to another directory (or change the file's name) use:
```
git mv someimagefile.png images/someimagefile.png
```

**Comment by Karczel** [comment]
done!
